FROM Ubuntu

# set a directory for the app
WORKDIR /app

# copy all the files to the container
COPY . .

# install dependencies
RUN pip install pandas scikit-learn flask gunicorn
# define the port number the container should expose
EXPOSE 5000

# run the command
CMD ["python", "./app.py"]
